version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: framety_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: framety123
      POSTGRES_DB: framety_dev
    ports:
      - "5432:5432"
    volumes:
      - framety_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  framety_postgres_data:
    driver: local
